spec-version: 0.36.0
name: strip-ansi
synopsis: Strip ANSI escape codes from strings

copyright: (c) 2025 Simon Hengel
author: Simon Hengel <sol@typeful.net>

ghc-options: -Wall

dependencies:
  - base == 4.*

source-dirs:
  - src

library: {}

tests:
  spec:
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec == 2.*
      - ansi-terminal
